name: 'github-action-test-compare'
description: 'Compare tests against production'
author: 'NearForm'
inputs:
  installCommand:
    required: false
    description: 'Install command for target branch'
    default: 'npm install'
  testCommand:
    required: false
    description: 'Test command for target branch'
    default: 'npm test'
  tests:
    required: false
    description: 'Root test folder to copy to target folder'
    default: 'test'
  targetFolder:
    required: false
    description: 'The folder for the target branch checkout'
    default: '__target__'
  label:
    required: false
    description: 'Name of a label to remove after action completion'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Check target branch
      if: github.event.pull_request.base.ref == ''
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('No target branch found.')

    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Checkout target branch
      uses: actions/checkout@v3
      if: ${{ !env.ACT }}
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        path: ${{ inputs.targetFolder }}

    - name: Copy tests
      shell: sh
      run: cp -R ${{ inputs.tests }} ${{ inputs.targetFolder }}

    - name: Install
      shell: sh
      working-directory: ${{ inputs.targetFolder }}
      run: ${{ inputs.installCommand }}

    - name: Run tests
      shell: sh
      id: run-tests
      working-directory: ${{ inputs.targetFolder }}
      continue-on-error: true
      run: ${{ inputs.testCommand }}

    - name: Find comment
      uses: peter-evans/find-comment@v2
      if: ${{ !env.ACT }}
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: '## Test compare ⚠️'

    - name: Find comment
      if: ${{ env.ACT }}
      shell: sh
      run: echo "${{ github.event.pull_request.number }}"

    - name: Create or update comment
      if: ${{ !env.ACT && steps.run-tests.outcome == 'success' }}
      uses: peter-evans/create-or-update-comment@v3
      with:
        author:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## Test compare ⚠️
          The tests within this PR have passed in the **${{ github.event.pull_request.base.ref }}** branch. 
          Therefore, if this PR is fixing existing behavior, the tests added are likely to not be testing the new behavior. Please review.
        edit-mode: replace

    - name: Create or update comment
      if: ${{ env.ACT && steps.run-tests.outcome == 'success' }}
      shell: sh
      run: echo "${{ steps.run-tests.outcome }} ${{ github.event.pull_request.number }}"

    - name: Remove label if specified
      if: ${{ !env.ACT && inputs.label }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ github.token }}
        script: |
          github.rest.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: ['${{ inputs.label }}']
          })
      continue-on-error: true

    - name: Remove label if specified
      if: ${{ env.ACT && inputs.label }}
      shell: sh
      run: echo "${{ inputs.label }}"

    - name: Check test success, fail action
      if: steps.run-tests.outcome == 'success'
      shell: sh
      run: exit 1

    - name: Check test failure, action success, delete comment
      if: steps.run-tests.outcome != 'success' && steps.find-comment.outputs.comment-id != ''
      uses: actions/github-script@v6
      with:
        github-token: ${{ github.token }}
        script: |
          github.rest.issues.deleteComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: ${{ steps.find-comment.outputs.comment-id }}
          })
