name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'The semver to use'
        required: true
        default: 'patch'
        type: choice
        options:
          - auto
          - patch
          - minor
          - major
      baseTag:
        description: 'base release tag'
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: nearform-actions/optic-release-automation-action@v4
        with:
          semver: ${{ github.event.inputs.semver }}
          base-tag: ${{ github.event.inputs.baseTag }}
          sync-semver-tags: 'true'
          build-command: npm ci
